### ISSUE TITLE
Setup and usage.

### ISSUE THREAD

**Issue by FreqMeister** [MerlinR/TTCNotifier#1]
Hey! Want to start with saying great work and idea. Having some issues with the setup and usage of it though! was hoping you might have more detailed instructions on how to make sure this is setup correctly and how to sue it. I think I have got it setup correctly, but when I try and add stuff I get a bunch of messages in the cmd and dont think it has added the item, as when I try the list command nothing shows. If I try and type in watch I seem to end up in a loop with the following argument is required: watch. A little confused as to what I am doing wrong, any help would be amazing!

**Comment by FreqMeister** [comment]
>> add https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?SearchType=Sell&ItemID=211&ItemNamePattern=Dreugh+Wax&ItemCategory1ID=&ItemTraitID=&ItemQualityID=&IsChampionPoint=false&LevelMin=&LevelMax=&MasterWritVoucherMin=&MasterWritVoucherMax=&AmountMin=&AmountMax=&PriceMin=&PriceMax= -p 8000
>> Process DreughWax:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\FreqMaister14\OneDrive\Documents\GitHub\TTCNotifier\ttcnotify\lib\searchItem.py", line 55, in __init__
    self.searchItem(item)
  File "C:\Users\FreqMaister14\OneDrive\Documents\GitHub\TTCNotifier\ttcnotify\lib\searchItem.py", line 91, in searchItem
    parsed.feed(parsed.webContent)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\html\parser.py", line 110, in feed
    self.goahead(0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\html\parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\html\parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "C:\Users\FreqMaister14\OneDrive\Documents\GitHub\TTCNotifier\ttcnotify\lib\htmlParser.py", line 104, in handle_endtag
    self.tradeList = sorted(filter(None, self.tradeList), key = lambda i: i['seen'])
  File "C:\Users\FreqMaister14\OneDrive\Documents\GitHub\TTCNotifier\ttcnotify\lib\htmlParser.py", line 104, in <lambda>
    self.tradeList = sorted(filter(None, self.tradeList), key = lambda i: i['seen'])
KeyError: 'seen'
